overrides:
  glob: '>=10.5.0'
  minimatch: '>=9.0.7'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - sharp
  - unrs-resolver

allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
